#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"

#include "tiger.h"
#include "celebrate.h"
#include "finish2.h"
#include "person1.h"
#include "tiger1.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  struct person1 dude;
  dude.row = 60;
  dude.col = 10;
  dude.count = 0;

  

  while (1) {
    waitForVBlank();
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      ///////////////////////////////////////////////////////////////////
      ////////////////////////// START //////////////////////////////////
      ///////////////////////////////////////////////////////////////////
      case START:
        drawFullScreenImageDMA(tiger);
        drawString(140, 80, "Press START", BLACK);
        // reset button
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          state = START;

        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          waitForVBlank();
          state = PLAY;
        }
        // state = ?
        break;
      //////////////////////////////////////////////////////////////////
      ////////////////////////// PLAY //////////////////////////////////
      //////////////////////////////////////////////////////////////////
      case PLAY:
        // reset button
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          dude.count = 0;
          dude.row = 60;
          dude.col = 10;
        }
        
        drawImageDMA(60, 200, 40, 40, finish2);
        drawImageDMA(dude.row, dude.col, 30, 30, person1);
        drawImageDMA(100, 100, 30, 30, tiger1);
        
        char count = dude.count + '0';
        drawString(140, 80, "Counter: ", WHITE);
        drawRectDMA(140, 140, 10, 10, BLACK);
        drawChar(140, 140, count, WHITE);
        waitForVBlank();
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (dude.row < 130) {
            dude.row++;
            undrawImageDMA(dude.row - 1, dude.col, 30, 30, person1);
            drawRectDMA(dude.row - 1, dude.col, 30, 30, BLACK);
            drawImageDMA(dude.row, dude.col, 30, 30, person1);
          }
        } 
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (dude.row > 0) {
            dude.row--;
            undrawImageDMA(dude.row + 1, dude.col, 30, 30, person1);
            drawRectDMA(dude.row + 1, dude.col, 30, 30, BLACK);
            drawImageDMA(dude.row, dude.col, 30, 30, person1);
          }
        } 
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (dude.col > 0) {
            dude.col--;
            undrawImageDMA(dude.row, dude.col + 1, 30, 30, person1);
            drawRectDMA(dude.row, dude.col + 1, 30, 30, BLACK);
            drawImageDMA(dude.row, dude.col, 30, 30, person1);
            
          }
        } 
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (dude.col < 210) {
            dude.col++;
            undrawImageDMA(dude.row, dude.col - 1, 30, 30, person1);
            drawRectDMA(dude.row, dude.col - 1, 30, 30, BLACK);
            drawImageDMA(dude.row, dude.col, 30, 30, person1);
            
          }
        } 
        waitForVBlank();
        if (dude.row < 100 + TIGER1_WIDTH && dude.row + PERSON1_WIDTH > 100 && dude.col < 100 + TIGER1_HEIGHT && dude.col + PERSON1_HEIGHT > 100) {
          state = LOSE;
        }
        if (dude.row < 60 + FINISH2_WIDTH && dude.row + PERSON1_WIDTH > 60 && dude.col < 200 + FINISH2_HEIGHT && dude.col + PERSON1_HEIGHT > 200) {
          if (dude.count == 2) {
            state = WIN;
          }
          dude.count++;
          undrawImageDMA(dude.row, dude.col, 30, 30, person1);
          dude.row = 60;
          dude.col = 10;
        }
        

        // state = ?
        break;
      /////////////////////////////////////////////////////////////////
      ////////////////////////// WIN //////////////////////////////////
      /////////////////////////////////////////////////////////////////
      case WIN:
        // reset button
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          state = START;
          dude.count = 0;
          dude.row = 60;
          dude.col = 10;
        }
      
        drawFullScreenImageDMA(celebrate);
        drawString(150, 100, "YOOO", BLACK);
        // state = ?
        break;
      //////////////////////////////////////////////////////////////////
      ////////////////////////// LOSE //////////////////////////////////
      //////////////////////////////////////////////////////////////////
      case LOSE:
        // reset button
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          state = START;
          dude.count = 0;
          dude.row = 60;
          dude.col = 10;
        }

        fillScreenDMA(BLACK);
        drawString(110, 80, "YOU LOSE :(", WHITE);
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
